version: '3.6'
services:
  iris:
    command: --check-caps false
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773:51773
      - 52773:52773
      - 1972:1972
    volumes:
      - ./:/irisdev/app
